apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: demo
  labels:
    app/name: app
    app/instance: blue
    app/version: "1.10"
spec:
  replicas: 3
  selector:
    matchLabels:
      app/name: app
      app/instance: blue
  template:
    metadata:
      labels:
        app/name: app
        app/instance: blue
        app/version: "1.10"
    spec:
      containers: 
        - name: nginx
          image: nginx:1.10
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 1
          volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: html
          configMap:
            name: content-blue
